### ISSUE TITLE
Необходимо починить Datagrid Native

### ISSUE THREAD

**Issue by abrgitlab** [glavweb/GlavwebDatagridBundle#2]
```
$datagridBuilder->addFilter('member.id');

$result = $datagridBuilder->build([
    'member.id' => $memberStub->getId()
])->getList();

```
Этот код отрабатывает неправильно.
Причина в том, что при парсинге фильтров datagrid подставляет свой основной алиас вместо join-алиаса таблицы поля member.

У меня решение есть, однако я не могу создать пулл-реквест.

**Comment by nilov** [comment]
Привет! 

Хорошо, покажи свое решение.

**Comment by nilov** [comment]
Спасибо, я понял, что ты имеешь ввиду. Действительно, ты прав, проблема была в этом. Исправил баг здесь https://github.com/glavweb/GlavwebDatagridBundle/releases/tag/v2.1.2
