### ISSUE TITLE
Будет ли поддержка symfony 5?

### ISSUE THREAD

**Issue by byhaskell** [glavweb/GlavwebDatagridBundle#4]
Здравствуйте. Хотел познакомиться с бандлом после прочтения статьи на хабре, но оказалось что на пятерку бандл не накатить. 
Планируется поддержка и примерно когда?

**Comment by nilov** [comment]
Здравствуйте! Да, будет, но не в ближайшее время. Вы можете попробовать исправить это в своем форке, а затем отправить пул-реквест.

**Comment by byhaskell** [comment]
@nilov Спасибо за ответ. 
Рассмотрю вариант с форком, может появится время, спасибо!)
